server:
  port: 9090

spring:
  application:
    name: msvc-product
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ProductosDb
    username: root
    password: ray123456
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: mysql
    #database-platform: org.hibernate.dialect.MySQLDialect
servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka